### PR TITLE
Prepare release of version 4011.0.1

### PR DESCRIPTION
**Pull request by murcake**
* Make code compile with z3 4.11.2

### CODE REVIEW

**Comment by IagoAbal** [comment]
Hi! Thanks and sorry for the long wait. The version number would be 411.0 rather than 4011.0.1, can you fix that?

**Comment by murcake** [comment]
> Hi! Thanks and sorry for the long wait. The version number would be 411.0 rather than 4011.0.1, can you fix that?

Sure

**Comment by murcake** [comment]
Hmm, Github is behaving weirdly. It doesn't update the PR with new commits in the source branch. I guess, that happens when you delete the head repository and then restore it again. I'll try reopening the PR once again and if it doesn't work, I'll open another PR.

**Comment by murcake** [comment]
Hmm, Github is behaving weirdly. It doesn't update the PR with new commits in the source branch. I guess, that happens when you delete the head repository and then restore it again. I'll try reopening the PR once again and if it doesn't work, I'll open another PR.

**Pull request closed without merging**
