### PR TITLE
instance MonadZ3 m => MonadZ3 (StateT s m), lazy and strict

### PR DESCRIPTION
**Pull request by 0xd34df00d**

### CODE REVIEW

**Comment by IagoAbal** [comment]
I did push these changes manually some time ago, so I'm closing the PR, thanks again!

**Comment by IagoAbal** [comment]
Ooops, sorry, no, I got confused with a similar but different PR. @0xd34df00d let me know if you're still interested in getting this merged.

**Comment by 0xd34df00d** [comment]
@IagoAbal yea, definitely still interested!

**Comment by IagoAbal** [comment]
Great! My Haskell might be rusty but I think that:
```haskell
instance MonadZ3 m => MonadZ3 (StLazy.StateT s m) where
  getSolver = StLazy.StateT $ \st -> fmap (\solv -> (solv, st)) getSolver
```
could be written as:
```haskell
instance MonadZ3 m => MonadZ3 (StLazy.StateT s m) where
  getSolver = lift getSolver
```
If you fix that and rebase against master (currently there are conflicts) then we can merge.
Thanks!

**Comment by IagoAbal** [comment]
Superseded by #73.

**Pull request closed without merging**
