### PR TITLE
More sorts makers: mkArraySortN, mkEnumerationSort, mkListSort

### PR DESCRIPTION
**Pull request by maurobringolf**
Merge #51 first, then the diff below should clean up to include just the relevant bits.

### CODE REVIEW

**Comment by IagoAbal** [comment]
Done merging #51!

**Review by IagoAbal — APPROVED** [review]
Thanks for another PR, this looks good! Could you please rebase?

**Comment by maurobringolf** [comment]
Ready to go :+1:

**Comment by IagoAbal** [comment]
Sorry that it took me so long! I've been kind of busy. But when this happens please feel free to ping me.

**Comment by maurobringolf** [comment]
No worries, thanks for merging :+1:

**Pull request merged**
