### PR TITLE
Scrub deleted features

### PR DESCRIPTION
**Pull request by strake**
Interpolation and `Z3_get_parser_error` are no more in the latest versions of Z3.

### CODE REVIEW

**Comment by IagoAbal** [comment]
Thanks, but please check that this does not duplicates 1ac16b01c38ebb717c16bd6e443b8d6b639ea2bb and 77af55a04f7ffd61295c866f4d598e43a98e4a9c (I believe it does).

**Comment by strake** [comment]
Whoops, never mind ☺

**Comment by IagoAbal** [comment]
Thanks a lot anyways, I plan to make a release tomorrow since I guess more and more people will encounter the same problem.

**Comment by meditans** [comment]
@IagoAbal maybe wait for my PR with the inclusion of the sequence interface?

**Comment by IagoAbal** [comment]
Sorry, I shouldn't have said "tomorrow" but ASAP. I'll look into @meditans PR but I'll seriously try to make that release happen this coming week...

**Pull request closed without merging**
