### PR TITLE
instance Semigroup Opts

### PR DESCRIPTION
**Pull request by strake**
Required to build on newer GHC

### CODE REVIEW

**Comment by IagoAbal** [comment]
Hi,

Thanks for letting me know, I forgot about this. But I cannot take the patch as it is, since we still want to support older versions of _base_. It will have to use some CPP, as in https://github.com/IagoAbal/haskell-bv/commit/e29d001a02558acc92faefb6469ad4e6705ee1b3.

If you want to do this yourself that would be great, otherwise I can look into that.

**Comment by strake** [comment]
PTAL

**Comment by IagoAbal** [comment]
It looks good, I'll merge it soon. Thanks!

**Comment by IagoAbal** [comment]
I have rebased your commits, edited the commit message, and merged the result into master: cf. f64e1d10c50. Thank you again!

**Pull request closed without merging**
