### PR TITLE
Murcake/steps to z3 4.11 support

### PR DESCRIPTION
**Pull request by murcake**
Continuation of #83

### CODE REVIEW

**Comment by nmeum** [comment]
So far this works well for me with Z3 4.12.2 and GHC 9.4.5.

@IagoAbal is there any chance that you could take a look at this? :pleading_face:

**Review by IagoAbal — APPROVED** [review]
Thanks!

**Comment by IagoAbal** [comment]
Hey sorry for being so bad at maintaining this package lately... I'll try to do a new release soon.

**Comment by temyurchenko** [comment]
> Hey sorry for being so bad at maintaining this package lately... I'll try to do a new release soon.

Life gets in a way sometimes, it's understandable. Thank you for doing the work

**Comment by arminhoh** [comment]
@IagoAbal Could you please have another look at this? I understand that you are busy, it is just pity, since the release is ready and just needs to be tagged and uploaded.

**Pull request merged**
