### PR TITLE
Sequences

### PR DESCRIPTION
**Pull request by meditans**
Hi, this PR should add bindings for the `Sequences and regular expressions` API in the `C.hsc`, `Base.hs` and `Monad.hs` modules, with relative documentation. Please review carefully the functions which manipulate lists, for example having arguments of type `[AST]`, because I want to make sure that I picked up onto the right patterns.

For discussion: in some functions in `Base.hs` where a `CUInt` is expected from the C API, it is passed a `(Integral int) => int`, and then a check is made to make sure that the integer is in fact >= 0. Now, in this PR I maintained that style, but I think that passing a `Natural` would be better, especially in the functions where multiple Ints are passed.

### CODE REVIEW

**Comment by IagoAbal** [comment]
> For discussion: in some functions in `Base.hs` where a `CUInt` is expected from the C API, it is passed a `(Integral int) => int`, and then a check is made to make sure that the integer is in fact >= 0. Now, in this PR I maintained that style, but I think that passing a `Natural` would be better, especially in the functions where multiple Ints are passed.

Thanks for taking a look at the other bindings and making the effort to keep the interface consistent.

At the time we started this project (back in 2012's?) I think `Natural` wasn't part of _base_, and changing this now would break compatibility with previous versions. Nonetheless in these cases I would like to have a few more opinions. In this case I think the natural choice (no pun intended!) would have been to use a `Word` type, `Natural` is not ideal since it has arbitrary precision. I think we chose to rely on `Integral` because we expected most people to use `Int` or `Integer`.

This is kind-of related to the on-going discussion of pull request #3 (perhaps you have an opinion on that one?).

I'm very much in favor of collecting ideas for a better interface and at some point, when there are enough ideas for improvement gathered, put them together and redesign these bindings. Then we break compatibility once but for a (hopefully) significant improvement. But I'm not in favor of breaking compatibility every now and then adding just one small improvement at a time.

**Comment by meditans** [comment]
Hi, I'll try to write at least an example for the new functions I wrote (or tests) asap. By the way the examples suffer from the fact that the `fail` function is not in the `Monad` typeclass anymore, and so many of the monadic bindings have to be declared irrefutable (I hope to update the examples in a subsequent PR).

Your position on `Int`/`Natural` is extremely reasonable and I totally agree, I'll take a look at the other issue you linked as soon as I can, thanks for the review!

**Comment by mpdairy** [comment]
What's the status of this PR? Can I do anything to help get it merged?

**Comment by IagoAbal** [comment]
Hi @mpdairy, I need a (few?) passing test case(s) added to https://github.com/IagoAbal/haskell-z3/blob/master/test/Z3/Base/Spec.hs. After that I'm happy to merge.

**Comment by IagoAbal** [comment]
OK, since this took some work to do and I presume it would be valuable for some... I'll merge anyways. I guess we're all to busy to add tests.

**Pull request merged**
